import { readStoredBrandName } from "@/lib/brand-store";

/** Organisation branding used across PDFs, exports and document headers. */
export const BRAND = {
  name: "Ethiopian Economic Association",
  shortName: "EEA",
  tagline: "Independent economic research for Ethiopia",
  address: {
    line1: "EEA / EEPRI Building, CMC Road",
    line2: "P.O. Box 34282",
    city: "Addis Ababa",
    country: "Ethiopia",
  },
  email: "info@eea-ethiopia.org",
  phone: "+251 11 645 3200",
  website: "www.eea-ethiopia.org",
  tin: "0000123456",
} as const;

/** Active brand name — honours the Settings override when present. */
export function activeBrandName(): string {
  try { return readStoredBrandName(); } catch { return BRAND.name; }
}

/** Single-line postal address used in PDFs / CSV headers. */
export function brandAddressLine(): string {
  const a = BRAND.address;
  return `${a.line1}, ${a.line2}, ${a.city}, ${a.country}`;
}

/** Header block (array of lines) used in CSV / text exports. */
export function brandHeaderLines(documentTitle: string): string[] {
  return [
    activeBrandName(),
    brandAddressLine(),
    `${BRAND.email}  ·  ${BRAND.phone}  ·  ${BRAND.website}`,
    `TIN: ${BRAND.tin}`,
    "",
    documentTitle,
    `Generated: ${new Date().toISOString().slice(0, 19).replace("T", " ")}`,
    "",
  ];
}

/** Footer block (array of lines) appended to CSV / text exports. */
export function brandFooterLines(): string[] {
  return [
    "",
    `— End of document —`,
    `${activeBrandName()}  ·  ${BRAND.website}  ·  TIN ${BRAND.tin}`,
    `This document was generated by the EEA Finance system. For questions contact ${BRAND.email}.`,
  ];
}
