/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TimeTrackingRouteImport } from './routes/time-tracking'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BudgetingRouteImport } from './routes/budgeting'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackingRoute = TimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetingRoute = BudgetingRouteImport.update({
  id: '/budgeting',
  path: '/budgeting',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/apps': typeof AppsRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/crm': typeof CrmRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/taxes': typeof TaxesRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/transactions': typeof TransactionsRoute
  '/invoices/new': typeof InvoicesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/apps': typeof AppsRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/crm': typeof CrmRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/taxes': typeof TaxesRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/transactions': typeof TransactionsRoute
  '/invoices/new': typeof InvoicesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/apps': typeof AppsRoute
  '/banking': typeof BankingRoute
  '/budgeting': typeof BudgetingRoute
  '/crm': typeof CrmRoute
  '/documents': typeof DocumentsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/payroll': typeof PayrollRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/taxes': typeof TaxesRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/transactions': typeof TransactionsRoute
  '/invoices/new': typeof InvoicesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/apps'
    | '/banking'
    | '/budgeting'
    | '/crm'
    | '/documents'
    | '/expenses'
    | '/inventory'
    | '/payroll'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/taxes'
    | '/time-tracking'
    | '/transactions'
    | '/invoices/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/apps'
    | '/banking'
    | '/budgeting'
    | '/crm'
    | '/documents'
    | '/expenses'
    | '/inventory'
    | '/payroll'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/taxes'
    | '/time-tracking'
    | '/transactions'
    | '/invoices/new'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/apps'
    | '/banking'
    | '/budgeting'
    | '/crm'
    | '/documents'
    | '/expenses'
    | '/inventory'
    | '/payroll'
    | '/projects'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/taxes'
    | '/time-tracking'
    | '/transactions'
    | '/invoices/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AppsRoute: typeof AppsRoute
  BankingRoute: typeof BankingRoute
  BudgetingRoute: typeof BudgetingRoute
  CrmRoute: typeof CrmRoute
  DocumentsRoute: typeof DocumentsRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  PayrollRoute: typeof PayrollRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  TaxesRoute: typeof TaxesRoute
  TimeTrackingRoute: typeof TimeTrackingRoute
  TransactionsRoute: typeof TransactionsRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking': {
      id: '/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgeting': {
      id: '/budgeting'
      path: '/budgeting'
      fullPath: '/budgeting'
      preLoaderRoute: typeof BudgetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AppsRoute: AppsRoute,
  BankingRoute: BankingRoute,
  BudgetingRoute: BudgetingRoute,
  CrmRoute: CrmRoute,
  DocumentsRoute: DocumentsRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  PayrollRoute: PayrollRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  TaxesRoute: TaxesRoute,
  TimeTrackingRoute: TimeTrackingRoute,
  TransactionsRoute: TransactionsRoute,
  InvoicesNewRoute: InvoicesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
